language: csharp
mono: none
dotnet: 2.1.301
before_script: cd TestAPI
script:
 - dotnet restore
deploy:
   provider: cloudfoundry
   username: richardfc83@gmail.com
   password: Jumpstart0.
   api: https://api.run.pivotal.io
   organization: TensorFlow
   space: development