language: csharp
mono: none
dotnet: 2.1.301
before_script: cd TestAPI
script:
 - dotnet restore
deploy:
   provider: cloudfoundry
   username: GregHowe
   password: r1ch4rdfc83.
   api: https://api.run.pivotal.io
   organization: TensorFlow
   space: development